---
development:
  cloud_name: divrxgmvf
  api_key: '996545259884265'
  api_secret: sFygmam92Lm5laeMUDalp3ejfHE
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: divrxgmvf
  api_key: '996545259884265'
  api_secret: sFygmam92Lm5laeMUDalp3ejfHE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: divrxgmvf
  api_key: '996545259884265'
  api_secret: sFygmam92Lm5laeMUDalp3ejfHE
  enhance_image_tag: true
  static_image_support: true
